"""初期シードデータ定義"""
from datetime import datetime

SEED_CREATED_AT = "2026-01-01T00:00:00Z"

# サービス機能マスター定義（19件）
SERVICE_FEATURES = [
    # service-001: テナント管理サービス
    {
        "id": "feature-service-001-01",
        "type": "service_feature",
        "service_id": "service-001",
        "feature_key": "audit_log",
        "feature_name": "監査ログ",
        "description": "テナント操作の監査ログを記録・保存する機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-001",
    },
    {
        "id": "feature-service-001-02",
        "type": "service_feature",
        "service_id": "service-001",
        "feature_key": "auto_backup",
        "feature_name": "自動バックアップ",
        "description": "テナントデータを定期的に自動バックアップする機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-001",
    },
    # service-002: 認証認可サービス
    {
        "id": "feature-service-002-01",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "mfa",
        "feature_name": "多要素認証 (MFA)",
        "description": "ログイン時にMFAを要求する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-002",
    },
    {
        "id": "feature-service-002-02",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "sso",
        "feature_name": "シングルサインオン (SSO)",
        "description": "外部IdPとのSSO連携を有効にする機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-002",
    },
    {
        "id": "feature-service-002-03",
        "type": "service_feature",
        "service_id": "service-002",
        "feature_key": "session_timeout",
        "feature_name": "セッションタイムアウト",
        "description": "一定時間操作がない場合に自動的にログアウトする機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-002",
    },
    # service-003: 利用サービス設定サービス
    {
        "id": "feature-service-003-01",
        "type": "service_feature",
        "service_id": "service-003",
        "feature_key": "service_usage_report",
        "feature_name": "サービス利用レポート",
        "description": "テナントのサービス利用状況をレポートとして出力する機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-003",
    },
    {
        "id": "feature-service-003-02",
        "type": "service_feature",
        "service_id": "service-003",
        "feature_key": "bulk_assignment",
        "feature_name": "一括サービス割り当て",
        "description": "複数テナントへのサービスを一括で割り当てる機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-003",
    },
    # service-004: ファイル管理サービス
    {
        "id": "feature-service-004-01",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "file_sharing",
        "feature_name": "ファイル外部共有",
        "description": "組織外へのファイル共有リンクを生成・管理する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-004",
    },
    {
        "id": "feature-service-004-02",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "large_file_upload",
        "feature_name": "大容量ファイルアップロード",
        "description": "1GB以上の大容量ファイルをアップロードする機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-004",
    },
    {
        "id": "feature-service-004-03",
        "type": "service_feature",
        "service_id": "service-004",
        "feature_key": "version_control",
        "feature_name": "バージョン管理",
        "description": "ファイルのバージョン履歴を管理・復元する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-004",
    },
    # service-005: メッセージングサービス
    {
        "id": "feature-service-005-01",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "external_notification",
        "feature_name": "外部通知連携",
        "description": "メール・Slack等の外部チャネルへの通知を送信する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-005",
    },
    {
        "id": "feature-service-005-02",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "message_archive",
        "feature_name": "メッセージアーカイブ",
        "description": "メッセージを長期保存・検索する機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-005",
    },
    {
        "id": "feature-service-005-03",
        "type": "service_feature",
        "service_id": "service-005",
        "feature_key": "broadcast",
        "feature_name": "一斉配信",
        "description": "全テナントユーザーへのメッセージを一括送信する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-005",
    },
    # service-006: API利用サービス
    {
        "id": "feature-service-006-01",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "rate_limit_override",
        "feature_name": "レート制限緩和",
        "description": "APIリクエストのレート制限を緩和する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-006",
    },
    {
        "id": "feature-service-006-02",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "api_key_management",
        "feature_name": "APIキー管理",
        "description": "テナント固有のAPIキーを発行・管理する機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-006",
    },
    {
        "id": "feature-service-006-03",
        "type": "service_feature",
        "service_id": "service-006",
        "feature_key": "usage_analytics",
        "feature_name": "利用分析",
        "description": "API利用状況の詳細分析レポートを提供する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-006",
    },
    # service-007: バックアップサービス
    {
        "id": "feature-service-007-01",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "scheduled_backup",
        "feature_name": "スケジュールバックアップ",
        "description": "指定したスケジュールで自動的にバックアップを実行する機能",
        "default_enabled": True,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-007",
    },
    {
        "id": "feature-service-007-02",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "cross_region_backup",
        "feature_name": "リージョン間バックアップ",
        "description": "異なるリージョンへのバックアップコピーを保持する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-007",
    },
    {
        "id": "feature-service-007-03",
        "type": "service_feature",
        "service_id": "service-007",
        "feature_key": "incremental_backup",
        "feature_name": "増分バックアップ",
        "description": "変更差分のみをバックアップして保存容量を削減する機能",
        "default_enabled": False,
        "created_at": SEED_CREATED_AT,
        "partitionKey": "service-007",
    },
]
