"""サンプルテナントの TenantServiceFeature データ定義"""

SAMPLE_TENANT_SERVICE_FEATURES = [
    # tenant-sample-001: ファイル外部共有を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-001_feature-service-004-01",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-004",
        "feature_id": "feature-service-004-01",
        "feature_key": "file_sharing",
        "is_enabled": True,
        "updated_at": "2026-01-15T09:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-001: バージョン管理を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-001_feature-service-004-03",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-004",
        "feature_id": "feature-service-004-03",
        "feature_key": "version_control",
        "is_enabled": True,
        "updated_at": "2026-01-15T09:05:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-001: MFA を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-001_feature-service-002-01",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-001",
        "service_id": "service-002",
        "feature_id": "feature-service-002-01",
        "feature_key": "mfa",
        "is_enabled": True,
        "updated_at": "2026-01-20T10:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-001",
    },
    # tenant-sample-002: MFA を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-002_feature-service-002-01",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-002",
        "service_id": "service-002",
        "feature_id": "feature-service-002-01",
        "feature_key": "mfa",
        "is_enabled": True,
        "updated_at": "2026-01-18T14:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-002",
    },
    # tenant-sample-002: 外部通知連携を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-002_feature-service-005-01",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-002",
        "service_id": "service-005",
        "feature_id": "feature-service-005-01",
        "feature_key": "external_notification",
        "is_enabled": True,
        "updated_at": "2026-01-18T14:10:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-002",
    },
    # tenant-sample-003: SSO を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-003_feature-service-002-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-003",
        "service_id": "service-002",
        "feature_id": "feature-service-002-02",
        "feature_key": "sso",
        "is_enabled": True,
        "updated_at": "2026-02-01T08:30:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-003",
    },
    # tenant-sample-003: レート制限緩和を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-003_feature-service-006-01",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-003",
        "service_id": "service-006",
        "feature_id": "feature-service-006-01",
        "feature_key": "rate_limit_override",
        "is_enabled": True,
        "updated_at": "2026-02-01T08:40:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-003",
    },
    # tenant-sample-003: リージョン間バックアップを有効化（デフォルト False → True）
    {
        "id": "tenant-sample-003_feature-service-007-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-003",
        "service_id": "service-007",
        "feature_id": "feature-service-007-02",
        "feature_key": "cross_region_backup",
        "is_enabled": True,
        "updated_at": "2026-02-01T09:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-003",
    },
    # tenant-sample-004: メッセージアーカイブを無効化（デフォルト True → False）
    {
        "id": "tenant-sample-004_feature-service-005-02",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-004",
        "service_id": "service-005",
        "feature_id": "feature-service-005-02",
        "feature_key": "message_archive",
        "is_enabled": False,
        "updated_at": "2026-02-10T11:00:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-004",
    },
    # tenant-sample-004: 利用分析を有効化（デフォルト False → True）
    {
        "id": "tenant-sample-004_feature-service-006-03",
        "type": "tenant_service_feature",
        "tenant_id": "tenant-sample-004",
        "service_id": "service-006",
        "feature_id": "feature-service-006-03",
        "feature_key": "usage_analytics",
        "is_enabled": True,
        "updated_at": "2026-02-10T11:15:00Z",
        "updated_by": "admin-user-001",
        "partitionKey": "tenant-sample-004",
    },
]
